services:
  db:
    image: mysql:5.7.22
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      TZ: America/Bahia
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: wordpress
    ports:
      - "3308:3306"
    networks:
      - wordpress-network
    volumes:
      - db_data:/var/lib/mysql
  wordpress:
    image: wordpress:latest
    volumes:
      - ./config/php.conf.upload.ini:/usr/local/etc/php/conf.d/upload.ini
      - wp_data:/var/www/html/wp-content
    environment:
      TZ: America/Bahia
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: docker
    ports:
      - "80:80"
    networks:
      - wordpress-network
networks:
  wordpress-network:
    driver: bridge
volumes:
  db_data:
  wp_data: